### ISSUE TITLE
How to validate ICFG?

### ISSUE THREAD

**Issue by kshitijgorde** [Sable/heros#30]
Within a scene transformer, I've used
```InterproceduralCFG icfg = new JimpleBasedInterproceduralCFG();```
to get an ICFG. Now, how do I know whether it's correct or not?. I want to generate an adjacency matrix from this graph. If I print out this icfg using toString() then it just prints out a huge string. 
Anyone knows how to atleast visualize this graph?. Or export it in some Graph language (like DOT?)

**Comment by ericbodden** [comment]
Hi again.

> Within a scene transformer, I've used
> InterproceduralCFG icfg = new JimpleBasedInterproceduralCFG();
> to get an ICFG. Now, how do I know whether it's correct or not?

I am not sure that’s a sensible question at all. What does correctness even mean for you? There is no program analysis tool in the world that is 100% sound.

> . I want to generate an adjacency matrix from this graph.

Why would that be a sensible thing to do?

> If I print out this icfg using toString() then it just prints out a huge string.

Yes that’s because an ICFG contains millions of nodes. It’s not meant to be printed.

> Anyone knows how to atleast visualize this graph?. Or export it in some Graph language (like DOT?)

We have specialized tools that visualize small portions of the graph at a time, depending on user interest. That’s the only sensible way I can think of visualizing an ICFG, as they are simply too large. It’s like trying to visualize the internet…

Best wishes
Eric

**Comment by ericbodden** [comment]
Hi again.

> >> Yes that’s because an ICFG contains millions of nodes. It’s not meant to be printed. Why is it printing millions of nodes when I basically have nothing in the program?. My sample program is class Main(){public static void main(String[] args){}}So, where are the million nodes coming from?. It sure isn't from my input!
> > . I want to generate an adjacency matrix from this graph. 


I am sorry but without knowing your setup I cannot possibly answer your questions. If you want to get good answers to your questions then you really have to make a systematic effort at describing what exactly is you want to achieve, what you tried, what result you expected and which result you obtained and how this differs.

Depending on the command-line option you used it may well be that Soot loads the entire Java runtime library. So maybe that explains the output you are seeing.

Best wishes
Eric Bodden
